export const themes = [
  { id: "active4d", name: "Active4D" },
  { id: "all-hallows-eve", name: "All Hallows Eve" },
  { id: "amy", name: "Amy" },
  { id: "birds-of-paradise", name: "Birds of Paradise" },
  { id: "blackboard", name: "Blackboard" },
  { id: "brilliance-black", name: "Brilliance Black" },
  { id: "brilliance-dull", name: "Brilliance Dull" },
  { id: "chrome-devtools", name: "Chrome DevTools" },
  { id: "clouds-midnight", name: "Clouds Midnight" },
  { id: "clouds", name: "Clouds" },
  { id: "cobalt", name: "Cobalt" },
  { id: "dawn", name: "Dawn" },
  { id: "dreamweaver", name: "Dreamweaver" },
  { id: "eiffel", name: "Eiffel" },
  { id: "espresso-libre", name: "Espresso Libre" },
  { id: "github", name: "GitHub" },
  { id: "idle", name: "IDLE" },
  { id: "katzenmilch", name: "Katzenmilch" },
  { id: "kuroir-theme", name: "Kuroir Theme" },
  { id: "lazy", name: "LAZY" },
  { id: "magicwb--amiga-", name: "MagicWB (Amiga)" },
  { id: "merbivore-soft", name: "Merbivore Soft" },
  { id: "merbivore", name: "Merbivore" },
  { id: "monokai-bright", name: "Monokai Bright" },
  { id: "monokai", name: "Monokai" },
  { id: "night-owl", name: "Night Owl" },
  { id: "oceanic-next", name: "Oceanic Next" },
  { id: "pastels-on-dark", name: "Pastels on Dark" },
  { id: "slush-and-poppies", name: "Slush and Poppies" },
  { id: "solarized-dark", name: "Solarized-dark" },
  { id: "solarized-light", name: "Solarized-light" },
  { id: "spacecadet", name: "SpaceCadet" },
  { id: "sunburst", name: "Sunburst" },
  { id: "textmate--mac-classic-", name: "Textmate (Mac Classic)" },
  { id: "tomorrow-night-blue", name: "Tomorrow-Night-Blue" },
  { id: "tomorrow-night-bright", name: "Tomorrow-Night-Bright" },
  { id: "tomorrow-night-eighties", name: "Tomorrow-Night-Eighties" },
  { id: "tomorrow-night", name: "Tomorrow-Night" },
  { id: "tomorrow", name: "Tomorrow" },
  { id: "twilight", name: "Twilight" },
  { id: "upstream-sunburst", name: "Upstream Sunburst" },
  { id: "vibrant-ink", name: "Vibrant Ink" },
  { id: "xcode-default", name: "Xcode_default" },
  { id: "zenburnesque", name: "Zenburnesque" },
  { id: "iplastic", name: "iPlastic" },
  { id: "idlefingers", name: "idleFingers" },
  { id: "krtheme", name: "krTheme" },
  { id: "monoindustrial", name: "monoindustrial" }
];
